# Dados agrupados a partir da sua lista original
# Formato: distrito -> lista de localidades

LOCALIDADES_AGRUPADAS = {
    "Água Grande": [
        "Aeroporto",
        "Aeroporto ",
        "Almas",
        "Almerim",
        "Amparo 2",
        "Atrás da Cadeia",
        "Avenida Amilcar Cabral",
        "Avenida Kwame N´Krumah",
        "Avenida Marginal 12 de Julho",
        "Avenida Marginal 12 de julho",
        "Avenida da Conceição",
        "Bairro 3 de Fevereiro",
        "Bairro Militar",
        "Bairro Quilombo",
        "Bairro Saton",
        "Bairro Verde",
        "Bairro de Aeroporto",
        "Bairro de Hospital",
        "Belém",
        "Blenda Rosa Das Neves",
        "Boa Morte",
        "Bobô Forro",
        "Bombom",
        "Búdo Búdo",
        "Búgué",
        "Café-Café",
        "Campo de Milho",
        "Chácra",
        "Correia",
        "Cruz Mami",
        "Diogo Nunes",
        "Diogo Simão",
        "Dolores",
        "Estádio 12 de Julho",
        "Ferreira Governo",
        "Fruta Fruta",
        "Fundação Popular",
        "Gongá",
        "Guadalupe",
        "Jardim Pensamento",
        "Lemos",
        "Lucumi",
        "Madre de Deus",
        "Margarida Manuel",
        "Mercado Coco Coco",
        "Mesquita",
        "Micoló",
        "Milagrosa",
        "Monta Alegre",
        "O Que Del Rei",
        "PONTA MINA",
        "Palha",
        "Palmar",
        "Pantufo",
        "Patrice Lumunba",
        "Pemá Pemá",
        "Penha",
        "Pete Pete",
        "Ponte Graça",
        "Ponta Mina",
        "Praia Cruz",
        "Praia Francesa",
        "Praia Gambôa",
        "Praia Lagarto",
        "Praia Largato",
        "Praça Yon Gato",
        "Quatro Caminho (Mé Chio)",
        "Quilombo",
        "Reta de Micolo",
        "Ribachada",
        "Riboque",
        "Riboque ",
        "Rio Lima",
        "Rotunda das Nações Unidas",
        "Rua 3 de Fevereiro",
        "Rua 3 de fevereiro",
        "Rua João de Deus",
        "Rua Martinho Pinto da Rocha",
        "Rua Moçambique",
        "Rua Padre",
        "Rua Patrice Lumumba",
        "Rua Presidente Samora Marchel",
        "Rua da Caixa",
        "Santarem",
        "Santo Amaro",
        "Santo António",
        "Santo Antonio",
        "Saton",
        "Satón",
        "São Gabriel",
        "São João",
        "São Marcos",
        "São Marçal",
        "Uba Cajú",
        "Vila",
        "Vila Dolares",
        "Vila Fernanda",
        "Vila Fernandes",
        "Vila Mareco",
        "Vila Maria",
        "Vila Mora",
        "Voz da América",
        "Água Arroz",
        "Água Bôbô",
        "Água Marçal",
        "Água Porca",
        "Água Serra"
    ],
    "Cantagalo": [
        "Cabalo Môlê",
        "Mato Cana",
        "Mestre António",
        "Picão Flor",
        "Pinheira",
        "Ponta das Palmeiras",
        "Riboque Santana",
        "Santana",
        "UBA-BUDO",
        "Ubá Budo",
        "Ubá-Budo-Praia-Santana",
        "Voz da América"
    ],
    "Caué": [
        "Angolares",
        "Malanza"
    ],
    "Lembá": [
        "Atrás do Prédio",
        "Bairro Rosema",
        "Benga",
        "Neves",
        "Ponta Figo",
        "Ponta figo",
        "Ribeira Funda",
        "Santa Catarina",
        "Vila",
        "Água Toma"
    ],
    "Lobata": [
        "Agostinho Neto",
        "Bela Vista",
        "Conde",
        "Correia",
        "Desejada",
        "Ferreira Governo",
        "Gongá",
        "Guadalupe",
        "Maria Isabel Fernandes Das Neves",
        "Micoló",
        "Monte Café",
        "Morro Peixe",
        "Palmar",
        "Penha",
        "Plancas Primeira",
        "Praia Largato",
        "Quatro Caminho (Mé Chio)",
        "Santarém",
        "Santo Amaro",
        "Uba Cabra"
    ],
    "Mé-Zóchi": [
        "Almas",
        "Almerim",
        "Amparo 2",
        "Belém",
        "Bobô Forro",
        "Bombom",
        "Búgué",
        "Caminho Novo",
        "Capela",
        "Cola Grande",
        "Cova Barro",
        "Cruzeiro",
        "Diogo Nunes",
        "Diogo Simão",
        "Favorita",
        "Lemos",
        "Madre de Deus",
        "Margarida Manuel",
        "Mateus dos Angolares",
        "Melhorada",
        "Milagrosa",
        "Monta",
        "Monte Café",
        "Obô Izaquente",
        "Pau Quiabo",
        "Pau Sabão",
        "Piedade",
        "Pinheira",
        "Ponte Que Deus fez",
        "Praia Melão",
        "Rio Lima",
        "San Ponjata",
        "Sanguê Bu",
        "Santa Margarida",
        "Santo Amaro",
        "Santo António",
        "Tanque Leitão",
        "Torres Dias",
        "Trindade",
        "Ubá Budo",
        "Vila Mora",
        "Vista Alegre"
    ],
    "Pagué": [
        "Atrás do Estadio",
        "Azeitona",
        "Rua nova",
        "Terra Prometida"
    ]
}

# Lista de distritos oficiais
DISTRITOS_OFICIAIS = ["Água Grande", "Mé-Zóchi", "Cantagalo", "Lobata", "Lembá", "Caué", "Pagué"]

def get_localidades_por_distrito(distrito: str) -> list:
    """Retorna todas as localidades de um distrito"""
    return LOCALIDADES_AGRUPADAS.get(distrito, [])

def get_distrito_por_localidade(localidade: str) -> str:
    """Retorna o distrito de uma localidade"""
    for distrito, localidades in LOCALIDADES_AGRUPADAS.items():
        if localidade in localidades:
            return distrito
    return None

def get_all_localidades() -> dict:
    """Retorna todas as localidades agrupadas"""
    return LOCALIDADES_AGRUPADAS

def get_estatisticas() -> dict:
    """Retorna estatísticas dos dados"""
    return {
        distrito: len(localidades) 
        for distrito, localidades in LOCALIDADES_AGRUPADAS.items()
    }
